import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/home/Navbar";

const inter = Inter({ subsets: ["latin"] });
const nunito_sans = Nunito_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={cn("scroll-smooth", nunito_sans.className)}>
        {children}
      </body>
    </html>
  );
}
